splunk/com/splunk/HttpService.java
tests/com/splunk/HttpServiceTest.java

Allow the client consumer of the library to override the SSLSocketFactory, in order to use another protocols different from the flawed SSLv3.

Allow setting the SSLSocketFactory, to avoid the SSLv3 security issue.

---

.travis.yml
README.md
build.xml
splunk/com/splunk/DistributedPeer.java
splunk/com/splunk/Index.java
splunk/com/splunk/ServiceInfo.java
tests/com/splunk/FiredAlertsTest.java
tests/com/splunk/HttpServiceTest.java
tests/com/splunk/IndexTest.java
tests/com/splunk/LicenseTest.java
tests/com/splunk/ResultsReaderTestFromExpectedFile.java
tests/com/splunk/SDKTestCase.java
tests/com/splunk/SearchJobTest.java
tests/com/splunk/SettingsTest.java
tests/com/splunk/TcpInputTest.java
tests/com/splunk/UdpInputTest.java
tests/com/splunk/UploadTest.java

This change adds the ability to run the SDK test suite using Travis CI.
Specifically, it includes:
1. Using the Travis CI Docker capabilities to download a container
running Splunk pre-built to run tests.
2. Fixes to various tests to make them work properly and not make
any assumptions on the running system.

Add Travis CI support for the Java SDK

---

splunk/com/splunk/ResourceCollection.java

There are conditions in SHC by which Splunk may not return proper namespacing information for some objects (mostly saved searches). This in turn causes
a break in an assumption that the SDK is making, so we need to properly
handle a case where the namespace info is empty.

Fix null namespaces

---

splunk/com/splunk/PasswordCollection.java
tests/com/splunk/PasswordTest.java

- Use both realm and username when get/remove password from PasswordCollection
- Keep compatible with old usage
- Unit tests

Accessing Password with realm & username

---

splunk/com/splunk/HttpService.java
tests/com/splunk/CookieTest.java
tests/com/splunk/ServiceTest.java

This should cover scenarios for search head clusters backed by load balancers that may insert additional cookies.
**This needs additional testing**

Add support for multiple cookies

---

launchers/shim/shim/shim.cpp

Resolve: #92 
I'm not very familiar with vc++ and windows process management. I try to create a job object and assign to this job. When this job handler destroyed, the java process will also be killed. 
I'm not sure I did the right thing but I verify it can work in windows. Correct me if I'm wrong. Thank you.

fix bug of java modular input launchers in windows may not kill java process when it be terminated

---

splunk/com/splunk/Value.java

Fix bug of Value.toDate(string value) is not thread safe.

Fix bug of Value.toDate(string value) is not thread safe.

---

splunk/com/splunk/DataModelField.java

Before Splunk 7, comment value was just a string but now, it's an object
`("comment": {"description": "The body of a message."}`

make datamodel compatible with the json response in 7.0

---

splunk/src/main/java/com/splunk/Service.java
splunk/src/test/java/com/splunk/ServiceTest.java

**Update:**
- Splunk token and bearer token set methods are added.

Methods for setting Splunk and Bearer token added.

---

examples/pom.xml
splunk/pom.xml

**Update:**
- Deploy plugin for splunk module removed and it will use its parent plugin for deployment. (Refer Issue #170 )
- Supporting comment has been added in examples/pom.xml file as we have skipped deployment there.

Deploy plugin is removed from splunk module.

---

splunk/src/main/java/com/splunk/HttpService.java
splunk/src/main/java/com/splunk/Service.java
splunk/src/main/java/com/splunk/ServiceArgs.java
splunk/src/test/java/com/splunk/ServiceTest.java

Ref #169
1. Added support to add custom headers in Service
2. Implemented method setHttpHeaders which accepts a headers map
3. Created method setCustomHeaders in HttpService.java to filter and store the map key-values
4. Finally in send method of HttpService.java the customHeaders are added
Rather than merging the custom map with the default one, I created a new protected variable to store the custom map
values. Please let me know if this is correct or not.

Added feature to add custom headers to Service

---

.github/workflows/test.yml
README.md
docker-compose.yml

**Update:**
- Login Examples using credentials & tokens are added.
- Example of fetching job using Search creation.

README.md updated with Test example

---

splunk/src/main/java/com/splunk/Receiver.java

**Update:**
- HTTP Request using format strings to insert user supplied data into the raw requests headers. So to prevent attackers to replace escape characters in request string. It is recommended to use the PrintWriter which allows us to bifurcate headers using **println** method instead of manually entering **\r\n** characters.
- Host in socket is removed as it should not be exposed to external users from request headers.

Headers modified in Socket creation.

---

splunk/src/main/java/com/splunk/Xml.java
splunk/src/main/java/com/splunk/modularinput/InputDefinition.java
splunk/src/main/java/com/splunk/modularinput/ValidationDefinition.java

**Update:**
- By default, document builder factory xml parsers allows expansion of external entities. So to prevent attackers to forge malicious content using external entities, these features are added.

External Entities restricted in XML factory.

---

.github/workflows/release.yml

**Update:**
- While release, api docs will be generated and compressed using zip tool.
- Using **upload-artifact** github-action module, it will allow us to download generated api docs zip till 90 days.

API docs upload automated

---

.github/workflows/release.yml
.github/workflows/test.yml
README.md
splunk/pom.xml
splunk/src/main/java/com/splunk/HttpService.java
splunk/src/main/java/com/splunk/Job.java
splunk/src/main/java/com/splunk/JobCollection.java
splunk/src/main/java/com/splunk/OutputServer.java
splunk/src/main/java/com/splunk/SavedSearch.java
splunk/src/main/java/com/splunk/Service.java
splunk/src/test/java/com/splunk/SearchJobTest.java

In Splunk 9.0 new changes to certain search endpoints are added via v2 endpoints and changes from GET to POST. SDK detects whether 9.x or later is being used and uses v2 endpoints if so.

SDK Support for splunkd search API changes

---

splunk/src/main/java/com/splunk/SavedSearch.java
splunk/src/test/java/com/splunk/SavedSearchTest.java

Code changes for issue #126 , as per user's request to add 'args' parameter for the history function of savedSearches. He suggested a code change and it works fine. Added test case as well for the same.

Added 'args' parameter for Saved Search History function

---

splunk/src/main/java/com/splunk/PasswordCollection.java
splunk/src/test/java/com/splunk/PasswordTest.java

Added check for presence of wildcard's in 'owner' and/or 'app' while creating or deleting a StoragePassword. Check and error message is kept consistent with the other SDKs.

Storagepassword's wildcard check for create and delete actions

---

splunk/src/main/java/com/splunk/HttpService.java
splunk/src/main/java/com/splunk/Job.java
splunk/src/main/java/com/splunk/JobCollection.java
splunk/src/main/java/com/splunk/Receiver.java
splunk/src/main/java/com/splunk/Service.java
splunk/src/main/java/com/splunk/ServiceInfo.java
splunk/src/main/java/com/splunk/SimpleCookieStore.java
splunk/src/test/java/com/splunk/CookieTest.java
splunk/src/test/java/com/splunk/IndexTest.java
splunk/src/test/java/com/splunk/ReceiverTest.java
splunk/src/test/java/com/splunk/ServiceTest.java

Updated the version check to check for "9.0.2" to enable v2 Search APIs

Updated version checks to enable v2 search APIs

---

splunk/src/main/java/com/splunk/HttpService.java
splunk/src/main/java/com/splunk/Service.java
splunk/src/test/java/com/splunk/ServiceTest.java

- re-fetch instancetype and version if not set within Service instance to avoid NPE
- also provide local IP as alternative to localhost, addressing issue with certain local workflows

Re-fetch instanceType if not provided

---

splunk/src/main/java/com/splunk/HttpService.java
splunk/src/main/java/com/splunk/Service.java

- added instance method in Service class to get list of cluster master hosts
- added static method in HttpService class to update list of Valid Hosts with Cluster Master Hosts

Feature added to include cluster master hosts for HostName verification

---

splunk/src/main/java/com/splunk/HttpService.java
splunk/src/main/java/com/splunk/Service.java
splunk/src/test/java/com/splunk/ServiceTest.java

- `autologin` flag added to enable SDK to re-login once the session has expired using available `username` and `password`.

New autologin feature
